/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export function ArcadeUnit({ scale = 0.5, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/ArcadeUnit-transformed.glb')
  const { actions } = useAnimations(animations, group)
  const { gl } = useThree()

  const [isDragging, setIsDragging] = useState(false)
  const previousPointer = useRef({ x: 0, y: 0 })
  const dragRotation = useRef({ x: 0, y: 0 })

  const handlePointerDown = (e) => {
    e.stopPropagation()
    setIsDragging(true)
    previousPointer.current = { x: e.clientX, y: e.clientY }
    gl.domElement.style.cursor = 'grabbing'
  }

  const handlePointerUp = () => {
    setIsDragging(false)
    gl.domElement.style.cursor = 'grab'
  }

  const handlePointerMove = (e) => {
    if (!isDragging) return
    const deltaX = e.clientX - previousPointer.current.x
    const deltaY = e.clientY - previousPointer.current.y

    dragRotation.current.y += deltaX * 0.01
    dragRotation.current.x += deltaY * 0.01

    previousPointer.current = { x: e.clientX, y: e.clientY }
  }

  useFrame((state) => {
    if (!group.current) return;

    if (isDragging) {
      group.current.rotation.y = dragRotation.current.y
      group.current.rotation.x = dragRotation.current.x
    } else {
      dragRotation.current.y += 0.0010
      group.current.rotation.y = dragRotation.current.y
      group.current.rotation.x = dragRotation.current.x
    }

    group.current.position.y =
      (props.position ? props.position[1] : 0) + Math.sin(state.clock.elapsedTime) * 0.2;
  });

  return (
    <group
      ref={group}
      {...props}
      scale={scale}
      dispose={null}
      onPointerDown={handlePointerDown}
      onPointerUp={handlePointerUp}
      onPointerLeave={handlePointerUp}
      onPointerMove={handlePointerMove}
    >
      <group name="Scene">
        <group name="RootNode">
          <group
            name="pCylinder194"
            position={[0.049, 9.503, -3.114]}
            rotation={[-Math.PI / 6, 0, 0]}>
            <mesh
              name="pCylinder194_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.pCylinder194_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group
            name="pPlane17"
            position={[-0.017, 9.694, -2.812]}
            rotation={[Math.PI / 3, 0, 0]}
            scale={2.184}>
            <mesh
              name="pPlane17_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.pPlane17_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group
            name="pPlane18"
            position={[-0.017, 9.679, -2.839]}
            rotation={[Math.PI / 3, 0, 0]}
            scale={2.184}>
            <mesh
              name="pPlane18_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.pPlane18_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group
            name="pPlane19"
            position={[-0.017, 9.665, -2.862]}
            rotation={[Math.PI / 3, 0, 0]}
            scale={2.184}>
            <mesh
              name="pPlane19_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.pPlane19_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
        </group>
        <mesh
          name="polySurface655_lambert5_0"
          castShadow
          receiveShadow
          geometry={nodes.polySurface655_lambert5_0.geometry}
          material={materials.lambert5}
        />
        <mesh
          name="polySurface667_lambert7_0"
          castShadow
          receiveShadow
          geometry={nodes.polySurface667_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <group name="polySurface789">
          <group name="polySurface803" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface803_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface803_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface804" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface804_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface804_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface805" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface805_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface805_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group
            name="polySurface806"
            position={[-0.023, 9.944, -2.376]}
            rotation={[-Math.PI / 6, 0, 0]}>
            <mesh
              name="polySurface806_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface806_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface807" position={[-0.032, 7.902, -1.184]}>
            <mesh
              name="polySurface807_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface807_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface808" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface808_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface808_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface809" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface809_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface809_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface810" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface810_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface810_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface811" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface811_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface811_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface812" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface812_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface812_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface813" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface813_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface813_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface814" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface814_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface814_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface815" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface815_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface815_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface816" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface816_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface816_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface817" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface817_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface817_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface818" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface818_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface818_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface820" position={[2.068, 10.056, -2.66]}>
            <mesh
              name="polySurface820_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface820_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface821" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface821_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface821_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface822" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface822_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface822_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface823" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface823_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface823_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface824" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface824_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface824_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface825" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface825_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface825_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
          <group name="polySurface826" position={[0, 9.836, -2.381]}>
            <mesh
              name="polySurface826_lightmass_0"
              castShadow
              receiveShadow
              geometry={nodes.polySurface826_lightmass_0.geometry}
              material={materials.lightmass}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ArcadeUnit-transformed.glb')