/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function NoodleShop(props) {
  const { nodes, materials } = useGLTF('/models/NoodleShop-transformed.glb')

  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.y += 0.003
  })

  return (
    <group {...props} dispose={null} ref={modelRef} rotation = {[0.3,0,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.geo_Garbadge_Bin_M_UniqueAssets_0.geometry}
        material={materials.M_UniqueAssets}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.geo_Kiosk_M_TrimSheet_0.geometry}
        material={materials.M_TrimSheet}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/models/NoodleShop-transformed.glb')